### ISSUE TITLE
proof-newsecurity

### ISSUE THREAD

**Issue by Limited111** [anishathalye/proof-html#16]
@Override
public void onResume() {
    super.onResume();

    //Register new broadcast receiver.
    LocakBroadCastManager lbm
 = localBrpadcastManager.getInstance(this);
     lbm.registerReceiver(receiver, filter);
}

**Comment by anishathalye** [comment]
?On Dec 1, 2024, at 2:22 AM, STMH ***@***.***> wrote:﻿
@OverRide
public void onResume() {
super.onResume();
//Register new broadcast receiver.
LocakBroadCastManager lbm

= localBrpadcastManager.getInstance(this);
lbm.registerReceiver(receiver, filter);
}
