### ISSUE TITLE
Allow missing href for a tag

### ISSUE THREAD

**Issue by roman-vasylenko** [anishathalye/proof-html#5]
Thanks for this GitHub action. It is really useful.

I am wondering if it is possible to add `allow_missing_href` parameter [available in HTMLProofer](https://github.com/gjtorikian/html-proofer#configuration). In my case, the workflow returns lots of  "`a` tag is missing a reference" errors which actually can be ignored.

**Comment by anishathalye** [comment]
Done! 786bab9af8983219684cd48d573922de73faf4df
